### PR TITLE
Validator dashboard fund requests add tabs

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
**Tabs**
✅ Alles 
❌ Beoordelaar nodig  
in Nijmegen  and Eemsdelta , "Beoordelaar nodig"  tab displayed accepted(with wrong label text). 

Screenshot 2024-10-11 at 14 10 26
 Should be like this
 Screenshot 2024-10-11 at 14 13 04

✅ In behandeling 
❌ Afgehandeld
Due to incorrect labels text the tabs counter incorrect count requests
Screenshot 2024-10-11 at 14 20 39

✅ no errors in the console
✅ checked in different implementations

**Labels**
✅ Rejected status has label "Geweigerd"(old /new application and assigned )
✅ Accepted  status has label "Geaccepteerd"(old /new application and assigned )
✅ Pending status has label "Beoordelaar nodig" (new application and Not assigned )
❌ Accepted application and Not assigned has label "Beoordelaar nodig"  instead of 
Accepted

Screenshot 2024-10-10 at 18 15 54

❌ Rejected application and Not assigned has label "Beoordelaar nodig"  instead of 
Rejected

Screenshot 2024-10-10 at 18 19 28

Same situation with 
this 
Screenshot 2024-10-11 at 13 54 01

✅ Needs additional information  status has label "Aanvullende informatie benodigd"(old/new application and assigned ) when validator request clarification
 
❌ Buiten behandeling geplaatst
Out of process status   has old text  instead of "Buiten behandeling geplaatst"
Screenshot 2024-10-11 at 13 05 22


❌ Action column is out of the border due to  long naming of the label 
Screenshot 2024-10-11 at 14 01 23

Zoom 100%
Screenshot 2024-10-11 at 14 11 42

Filters:
New statuses not added in filter Status. 
Screenshot 2024-10-11 at 14 16 37

**Comment by aghimpu** [comment]
>> Filters:
New statuses not added in filter Status.

I think this should be avoided because they aren't real 'statuses' and more like a group of statuses to simplify the fund request processing for validators, while the dropdown filter contains real status values. Combining their values could also create some issues or at least confusion (also both the tabs and dropdown filters have separate url query parameters and it might cause a "conflict").

From what I understood in the issue description this isn't a requirement right now - "If needed more precise filters can be applied using the regular filters, for example in case of being on the alles tab and filtering for accepted requests."


>> ❌ Action column is out of the border due to long naming of the label
I discussed it with @dev-rminds and it will be fixed in another issue that is about adding a scrolling bar to multiple tables https://github.com/teamforus/SIU-2024-Standardisation-and-Improvement-of-the-UX/issues/20

**Review by irinaBerendeeva87 — DISMISSED** [review]
### Checked:
I think we should change  the naming  in filter of status  "Niet beoordeeld"
 due to change the naming of the status from Niet beoordeeld to "Aanvullende informatie benodigd"
 
Screenshot 2024-10-13 at 11 44 21

and based on the disign
Screenshot 2024-10-13 at 11 56 52

####  Not fixed :
Status:
❌ Buiten behandeling geplaatst
Out of process status has old text instead of "Buiten behandeling geplaatst"

#### Fixed:
**Labels**
- Beoordelaar nodig
- Accepted application and Not assigned has label "Beoordelaar nodig" instead of
Accepted
- Rejected application and Not assigned has label "Beoordelaar nodig" instead of
Rejected
- Out of process

"Action column is out of the border due to long naming of the label" will be fixed in another ticket 

**Tabs**
-  Alles
- Beoordelaar nodig
- In behandeling
- Afgehandeld

✅ no errors in the console
✅ checked in different implementations

**Comment by aghimpu** [comment]
> "Niet beoordeeld"

"Niet beoordeeld" is the label we already had for the disregarded fund requests, while "Aanvullende informatie benodigd" is something we added for fund requests that have pending clarifications. So if I understand it correctly then there's no need to change the text from "Niet beoordeeld" to "Aanvullende informatie benodigd"

**Comment by aghimpu** [comment]
> ❌ Buiten behandeling geplaatst

Changed to 'Buiten behandeling geplaatst' everywhere including the filter

**Comment by lexlog** [comment]
@aghimpu could you please check small merge conflict

**Review by lexlog — APPROVED** [review]

**Pull request merged**
