### PR TITLE
reimbursements dashboard page enhancements

### PR DESCRIPTION
**Pull request by aghimpu**
## Changes description & testing suggestions
List of changes:
- reimbursements table is now scrollable
- table now uses the new dropdown menu design for actions (instead button)
- fix the misalignment of elements in the card header
- the page is now using the new fund selector design (dropdown)

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by dev-rminds — DISMISSED** [review]
@aghimpu 
There is a small issue on the page:
image

Also I forgot to add "save filters in the url" to the list form the issue, since it's it will not increase the scope much, let's implement this as well.

**Comment by dev-rminds** [comment]
Not related to current PR, but while reviewing the changes I noticed reimbursement categories page looking a little off and fixed it.  

Before:
image


After:
image

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
❌ there is no option 'Choose funds' in dropdown 
Screenshot 2024-09-20 at 10 47 00
❌ Text "Fonds" instead of "Selecteer fonds"
✅ Action column in line 
❌ error in the console after refresh page 
Screenshot 2024-09-20 at 10 53 44
❌ if remove fund_id from the URL, then after refresh page  drop down keep its state  with chosen fund

**Comment by lexlog** [comment]
@aghimpu can you please check comment with feedback above?

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
❌ if choose the fund in the  dropdown then refresh the page  and  firstly we can see Funds(on 0:16sec)  and then chosen fund in the dropdown 
https://github.com/user-attachments/assets/a4a8d6ee-8e76-41b0-8840-188ae5a76f19

✅ option 'Choose funds' in dropdown
✅ 'Choose funds' in dropdown
✅ Action column in line

**FIXED**  if remove fund_id from the URL, then after refreshing page drop-down keep its state with chosen fund

Error in a console fixed somehow

**Comment by aghimpu** [comment]
> ### Checked:
> ❌ if choose the fund in the dropdown then refresh the page and firstly we can see Funds(on 0:16sec) and then chosen fund in the dropdown https://github.com/user-attachments/assets/a4a8d6ee-8e76-41b0-8840-188ae5a76f19

The same thing is happening on other pages as well, for example I could reproduce it on the vouchers page for a few other funds. Unfortunately atm I don't have a solution for this and it would need some research and if so then there's a chance we can fix it everywhere.
I think we should create a separate issue for this.

**Review by irinaBerendeeva87 — APPROVED** [review]
@aghimpu I have checked this case. ok) I have approved but wait this :
"save filters in the url"

**Comment by irinaBerendeeva87** [comment]
@aghimpu  could you provide information about the time when you could add  this  "save filters in the URL" ?

**Comment by aghimpu** [comment]
> @aghimpu could you provide information about the time when you could add this "save filters in the URL" ?

@irinaBerendeeva87 this was already added and it also passed the review from @dev-rminds

**Comment by aghimpu** [comment]
Screenshot from 2024-10-08 13-53-19
On page reload you can also see the information based on your selection

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked:
✅filters in the URL
✅ no errors in the console
✅ error 422 
✅ checked in different implementations

**Pull request merged**
