### PR TITLE
home page products block cms

### PR DESCRIPTION
**Pull request by dev-rminds**
## Changes description & testing suggestions

Test scope: current feature and create/edit other cms pages (including page cms blocks and faq)

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked 
**Title**
✅  error messages(long)
❌ title  alignment should be centered like in Prod env (https://vergoedingen.nijmegen.nl/fondsen/26)

**Markdown**
❌ the table insert at the top of the input field
✅ style

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 
> ❌ title alignment should be centered like in Prod env (https://vergoedingen.nijmegen.nl/fondsen/26). 

The title alignment is synchronised with markdown alignment for consistency.  
To change the alignment of the title you need to change the alignment of the text.
If you think we don't need it I can remove the synchronisation. 
image



> **Markdown** ❌ the table insert at the top of the input field. 

This issue is not related to current changes and we already have an issue about this problem: https://github.com/teamforus/DevOps/issues/947

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 
- removed the synchronization between products block cms text alignement and the title
- changed so that if there are no action products on the implementation, it shows the cms text on the budget products block
- if they are there, it shows only on action products
- changed section titles (including products) to be aligned to left to match production styles (prev. aligned to center)

**Review by irinaBerendeeva87 — APPROVED** [review]
**Checked**:
✅  title alignment

**Pull request merged**
