### PR TITLE
Add fund request redirect if user not authenticated, fund request style improvements on fund activate page

### PR DESCRIPTION
**Pull request by ateamcms**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:

✅  button Bekijk de aanvraag in email and on the page /activeer 
❌ Title, subtitle, and information don't relate to the actual status of the application. 
Even if application was approved/partially approved  the requester can see  the title 
Application in progress and the information text :
**The request has been rejected. An email has been sent with more information. 
Press the button below to view the details of the request.** 
Screenshot 2024-10-08 at 11 17 57

✅ checked in different implementations

--------------------------
 
 **Not related to this PR**
 ❌  no errors in the console 
 when there are 2 opened tabs with different accounts but one of them with expired access token and another with active. 
if close old one and reload active then Requester got a 403 error   after reloading the page  /fondsen-aanvraag/495. after reloading page keeps error. 

Screenshot 2024-10-08 at 10 56 14

**Comment by ateamcms** [comment]
@irinaBerendeeva87 updated texts, not related to this PR not fixed for now

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
❌ screen with reject fund application  blocking new application

https://github.com/user-attachments/assets/a96c74b2-c9fa-44e1-9496-e145ddb16314

❌ information block has the hardcode text  that the application was rejected but actually it was accepted. 

Screenshot 2024-10-10 at 14 45 58
✅ no errors in the console
✅ checked in different implementations

--------------------------
 
 **Not related to this PR**

**Review by irinaBerendeeva87 — APPROVED** [review]
Checked: fixed
- Blocker with reject screen fixed by not to show requester if his application was rejected. Instead of rejected screen we show the apply again screen. 
-  information block

**Pull request merged**
