### PR TITLE
Add payment type to sponsor transactions table

### PR DESCRIPTION
**Pull request by ateamcms**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — COMMENTED** [review]
### Checked:
**Side menu:**
❌ Page name is Betaalopdrachten
Screenshot 2024-08-28 at 16 43 46
**Page title** 
✅ Individuele betaalopdrachten
❌ Page name is Bulk betaalopdrachten
Screenshot 2024-08-28 at 16 56 19

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked :
**Provider**
✅ Betaalopdrachten instellingen
✅ Individuele betaalopdrachten

**Sponsor**
**Soort**
✅ Soort  is present
❌  text "Soort" should be bold/boldface
like other text
Screenshot 2024-08-30 at 15 12 54

❌  not possible to sort this field 
❌ No hover effect 
❌ Not displayed "Declaratie"   instead of displaying uitbetaling. 
✅ More button
**Side menu:**
✅ Page name is Betaalopdrachten

**Page title** 
✅ Page name is Bulk betaalopdrachten
**Out of the scope:**
Let us add the possibility of filter sorting.  Now we cannot to filter  it:

Screenshot 2024-08-30 at 16 16 00

**Comment by ateamcms** [comment]
@irinaBerendeeva87 fixed "Not displayed "Declaratie" instead of displaying uitbetaling." with commit to backend.

For style fixing I need some time to discuss it with Valentin, will go to the next week

**Comment by lexlog** [comment]
@irinaBerendeeva87 please approve PR if all fine except soort field

**Review by irinaBerendeeva87 — APPROVED** [review]
Checked:

✅ displayed "Declaratie"
Others will be fixed later.

**Pull request merged**
