### PR TITLE
Webshop add payouts details

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [x] *Check that dusk tests are working locally on compatible branch*
- [x] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by aghimpu** [comment]
Small note - the search input was moved to the bottom of the sidebar for consistency. We have all the filters in that place for other pages. 
Also the payout date on the fund request details page might be hidden by default if the transfer didn't happen yet.

**Comment by aghimpu** [comment]
The id on the expandable part of the payout transaction card was removed as well during the PR review, because we decided that it would be better to implement something similar to https://github.com/teamforus/SPO-2024-Smart-payout/issues/47 . Right now we just don't have any unique number for payout transactions that would look similar to what we have in the design.

**Comment by irinaBerendeeva87** [comment]
@aghimpu  I try to test this pr but when I did the payout for requester , requester did not see  any paouts  on the Payouts page on webshop. 
Screenshot 2024-10-11 at 20 36 09
Screenshot 2024-10-11 at 20 39 26

**Comment by aghimpu** [comment]
It should display just the payouts received when the requester complete a fund request, the ones generated in csv uploads of sponsor dashboard are ignored.

**Comment by lexlog** [comment]
@aghimpu could you please check minor merge conflict and merge develop after into branch

**Comment by lexlog** [comment]
status - PR is blocked by error when applying for payouts fund, needs investigation with devs
image

**Review by lexlog — APPROVED** [review]

**Pull request merged**
