### PR TITLE
Add website homepage, navbar, footer, roles, about us pages

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by lexlog** [comment]
status - was given some minor early feedback on Friday while testing some website parts

**Comment by MariaForus** [comment]
@aghimpu I'll start adding my feedback for the website elements related to this pull request. 

### Homepage

- [ ] The title for “Samenwerken aan het maximaliseren van sociale impact” appears oddly formatted on my laptop; if possible, "het maximaliseren" should be displayed on a single line. 

image


- [ ] "Read more" (Lees meer) function is not working, and there is incorrect text present. 
image

- [ ] Regarding the "Unieke aspecten" section, as a user, I cannot see which aspect of the platform I’m currently viewing. In the design, the icon changes to blue when a specific aspect is being viewed, and the arrow also turns blue. Now, the blue icon remains permanently visible on the "efficiente uitbetalingen" section. It should change according to what is shown. 
image

The buttons on the homepage are now working yet, but I suppose this will happen later on.

**Comment by MariaForus** [comment]
@aghimpu I'm continuing adding the feedback. 

21.08.2024 

**General note** 

- [ ] All pages don't have correct urls. All the pages should have Dutch urls as indicated in[ this issue. ](https://github.com/teamforus/WEB-2023-website-forus/issues/161)

### Roles pages

### Overview page

- [ ] The "roles" blocks appear are stacked on top of each other and not next to each other.

image

### Aanvrager/deelnemer 

- [ ] In the intro text, there is a space missing before “Zodra”. Also and “aanvrager” and “deelnemer” should be written in cursive.
image

- [ ] There is a button missing, it should lead to the demo aanvraag page.

How it is now: 
image

How it should be:
image

### Aanbieder

- [ ] In the intro text there are spaces missing - ("Zijn. Het" and "Door toegang"). The sentence starting from “Het Forus-systeem” should begin in the next line. 

image

### Sponsor

- [ ] In the intro text there are spaces missing. The sentence starting from “Het Forus-systeem” should begin in the next line. 
image

- [ ] I noticed I did't add the links in certain places (my fault). Please add the links in the following places: 

Link to "Fonds" page
image

Link to managementinformatie page
image

Links to CMS page and Websites (de voorkant van het systeem)
image

- [ ] In "Stap 10" there is an incorrect text (copied from stap 9). The right text can be found in Figma
image

### Beoordelaar 

- [ ] In the intro text there are spaces missing. (It should be "aanvraag toegekend" "alle details" "door de" "zoals sociale"
image

- [ ] In the Stap 5 there is a weird text. It should be removed.
image

### Over ons
### Ons verhaal 

- [ ] In the intro text there is 2 times “vinden” in the text. One “linden” should be removed. That’s probably my fault, sorry. 
image

- [ ] Incorrect alt text for this image: It should be "De verbindingen van sociale initiatieven via het Forus-platform” and now (from what I see it’s “Social initiatives”)
image

- [ ] There is a Link missing in the step 9 - Project Innovatiebudget 2023 

How it is now: 
image

How it should be:
image

- [ ] In “Onze waarden” part in “transparantie” text there is a link missing —> it should lead to Github van Forus
image

- [ ] The is not enough space between those elements. Can we add more space here?

image

- [ ] In the last part of the page there is a CTA missing, and the picture should be changed. @sashooa can you please help with the right picture without Ede and only municipalities that are on the homepage?
image

### Project Innovatiebudget 2023

- [ ] Alt text for this image is wrong. It should be "Gebruiksvriendelijk platform”. 

image

**Comment by aghimpu** [comment]
@MariaForus 
>> The "roles" blocks appear are stacked on top of each other and not next to each other.
Not really sure when and how exactly this happens, do you have any ideas on how to easier reproduce it (for some reason it didn't happen while I was testing this block).?

>> "Read more" (Lees meer) function is not working, and there is incorrect text present.
I added some random text for now, can you update it later?

>> Forus logo is not clickable when you’re on the homepage. Is there a reason for it? Better to have it clickable
How do you expect it to work? Should it reload the page or so?. I also made it so the menu dropdowns will close on Forus logo click as it was quite confusing sometimes.

>> The buttons on the homepage don't work, but I guess that will be resolved later on.
I added links to the existing pages in multiple places (not just on the homepage), but I'll add some more in other PR (we don't have all the pages to do it here properly either)

>> In the last part of the page there is a CTA missing, and the picture should be changed. @sashooa can you please help with the right picture without Ede and only municipalities that are on the homepage?
Will proceed with this one later


@lexlog 
>> The download links for the Me-app are incorrectly assigned: the Google Play icon directs users to the App Store, while the App Store icon leads to Google Play. These links need to be switched.

Can you please check these links in the env file as they are coming from there?


Everything else is fixed I believe.

**Comment by lexlog** [comment]
@aghimpu thanks for fixes

about android & ios links - they are configured from this file 
https://github.com/teamforus/server-configuration/blob/develop/frontend_env_configs/dev/react/env.js#L109
and parameters there look correct, is it possible that on website they are flipped?

another note
@MariaForus could you please validate that feedback you left is fixed?
changes are deployed on https://dev.forus.io/website/#/

**Comment by MariaForus** [comment]
@aghimpu thank you for the fixes. @lexlog Most of the feedback is applied, there are still minor things I notice, maybe they will be added later on, but I'm adding them here just to double-check. 

- [ ] Homepage: I notices that "Lees meer" and "Lees minder" are not right. They should be switched, so first we the user sees less text they should see the button"Lees meer" to read more and when the text is fully unfolded they should see the button "Lees minder" to see less text
image

@aghimpu here you can find the correct text for this part: https://docs.google.com/document/d/19HMahJQ4WvzYDWuFnL_KmUWqrpA8gFwuU0jrf69GbQQ/edit 

- [ ] Maybe this will happen later on but this button ("Ik wil meer weten") on the "Aanvrager" page is not get clickable
image

- [ ] On the sponsor page, there are no links yet that I requested, but again maybe it will be developed later on

- [ ] Over ons page: we're still missing the right image, @sashooa please let us know when you'll have the image ready. Also, there is a button missing. 

image

**Comment by aghimpu** [comment]
> about android & ios links - they are configured from this file https://github.com/teamforus/server-configuration/blob/develop/frontend_env_configs/dev/react/env.js#L109 and parameters there look correct, is it possible that on website they are flipped?

Thanks for checking it out. I double checked the website again and it seems like the image names were also flipped which confused me at first. That block is fixed in the most recent commit though.

**Comment by aghimpu** [comment]
> @aghimpu thank you for the fixes. @lexlog Most of the feedback is applied, there are still minor things I notice, maybe they will be added later on, but I'm adding them here just to double-check.
> 
> * [ ]  Homepage: I notices that "Lees meer" and "Lees minder" are not right. They should be switched, so first we the user sees less text they should see the button"Lees meer" to read more and when the text is fully unfolded they should see the button "Lees minder" to see less text
>   image
> 
> @aghimpu here you can find the correct text for this part: https://docs.google.com/document/d/19HMahJQ4WvzYDWuFnL_KmUWqrpA8gFwuU0jrf69GbQQ/edit
> 
> * [ ]  Maybe this will happen later on but this button ("Ik wil meer weten") on the "Aanvrager" page is not get clickable
>   image
> * [ ]  On the sponsor page, there are no links yet that I requested, but again maybe it will be developed later on
> * [ ]  Over ons page: we're still missing the right image, @sashooa please let us know when you'll have the image ready. Also, there is a button missing.
> 
> image

I didn't add the links to the pages that weren't added with this PR, many of them don't even have routes in the current one. This PR is just about the homepage (inc the navbar / footer), about us and roles pages. We'll just have to double check them later in other PRs.

I just fixed everything else but those links and the image (because it's not ready yet)

**Comment by lexlog** [comment]
@MariaForus could you please repeat comment with what's left now? we are planning to merge this and other branches to another branch, where we will combine all changes

**Comment by MariaForus** [comment]
@lexlog Changes left to adjust:

- [ ] Homepage: I notices that "Lees meer" and "Lees minder" are not right. They should be switched, so first we the user sees less text they should see the button"Lees meer" to read more and when the text is fully unfolded they should see the button "Lees minder" to see less text
image

- [ ] Add the correct text to the part mentioned above. The correct text for this part can be found here:  https://docs.google.com/document/d/19HMahJQ4WvzYDWuFnL_KmUWqrpA8gFwuU0jrf69GbQQ/edit 

- [ ] Over ons page: we're still missing the right image, @sashooa mentioned he'll have the image ready today
- [ ] There is a missing CTA button. 

image

**Comment by aghimpu** [comment]
> @lexlog Changes left to adjust:
> 
> * [ ]  Homepage: I notices that "Lees meer" and "Lees minder" are not right. They should be switched, so first we the user sees less text they should see the button"Lees meer" to read more and when the text is fully unfolded they should see the button "Lees minder" to see less text
>   image
> * [ ]  Add the correct text to the part mentioned above. The correct text for this part can be found here:  https://docs.google.com/document/d/19HMahJQ4WvzYDWuFnL_KmUWqrpA8gFwuU0jrf69GbQQ/edit
> * [ ]  Over ons page: we're still missing the right image, @sashooa just made it. @aghimpu It can be found in Figma.
> 
> image
> 
> * [ ]  There is a missing CTA button.
> 
> image

They were fixed few hours ago (except the image which requires redesign as well), but it doesn't look like  the changes were redeployed on https://dev.forus.io/website/#/

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-frontend-react/pull/281
A PR with all the pages combined, except login pages which will be added soon.

**Pull request closed without merging**
