### PR TITLE
add filter per year for financial overview statistics

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [x] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: financieel-dashboard-overzicht
❌ dropdowns retains their states  when changing implementation
❌ URL does not have  a parameter  when chosen different year

https://github.com/user-attachments/assets/f5fd849c-ce20-408b-8595-1f9127421e5d

**Balance and expenses**
✅ "Selecteer export type" modal
✅ dropdown
✅ hover
**Tegoeden**
✅ "Selecteer export type" modal

✅ dropdown
✅ hover
❌ incorrect data on the table(Nijmegen 2024/23 year)
Screenshot 2024-10-24 at 11 03 52

✅ checked in different implementations

**Comment by aghimpu** [comment]
> ### Checked: financieel-dashboard-overzicht
> ❌ dropdowns retains their states when changing implementation

@irinaBerendeeva87  The dropdowns are not supposed to retain their state when changing the organization in our organization switcher. It's not implemented on other pages and it's hard to implement such a behavior just for this particular case.

I added a URL query parameter like requested though.

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
**fixed** 
- dropdowns retains their states when changing implementation
- URL does not have a parameter when chosen different year
- incorrect data on the table(Nijmegen 2024/23 year)
**Balance and expenses**
✅ "Selecteer export type" modal
✅ dropdown
✅ hover

**Tegoeden**
❌ "Uitgaven " column  in csv file and in the page  has a different value 
Screenshot 2024-10-30 at 15 32 28

❌ moving animation while  changing year in dropdown 
 
https://github.com/user-attachments/assets/0ae55462-e2c3-4b09-991d-46eea3c79e99

❌ all funds are displayed 
Not all funds are displayed in Tegoeden in Groningen impl.  
in DB there is 4 funds but displayed only one.  in backend response there is also 4 funds
Screenshot 2024-10-31 at 10 56 49


Screenshot 2024-10-31 at 10 48 30

 ❓ Eemsdelta impl. has payouts in Tegoeden but download file without fund with type= payout
 
 
Screenshot 2024-10-31 at 11 39 05

 
✅ no errors in the console
✅ error 422 
✅ checked in different implementations

--------------------------
 
 **Not related to this PR**

**Comment by aghimpu** [comment]
@irinaBerendeeva87 in the second table we are displaying just the funds that have type = 'budget', so last 2 points (❌ all funds are displayed and ❓ Eemsdelta impl. has payouts in Tegoeden but download file without fund with type= payout) aren't valid

**Comment by irinaBerendeeva87** [comment]
> @irinaBerendeeva87 in the second table we are displaying just the funds that have type = 'budget', so "❌ all funds are displayed" isn't valid. So the funds being filtered based on that was done on purpose, it was always working like that.

Thanks. I got it.

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:

fixed:
 - "Uitgaven " column in csv file and in the page has a different value
 
 Not fixed:
- moving animation while changing year in dropdown

https://github.com/user-attachments/assets/16a96803-0815-461e-be41-40db96901911

- all funds are displayed(Groningen)

✅ checked in different implementations

**Comment by irinaBerendeeva87** [comment]
> > Not fixed:
> 
> * moving animation while changing year in dropdown
> 
> I added a loader instead of the table section while the fund statistics request is being processed and it seems to fix the issue sometimes, but apparently it still happens. I'm not really sure what a proper fix would be.

This behavior is not  a blocker so we can fix it later

**Review by irinaBerendeeva87 — APPROVED** [review]
Small problem with animation is not a bloker.  So I approve this PR

**Pull request merged**
