### PR TITLE
add duplicates picker modal confirmation for low amount vouchers upload

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by dev-rminds** [comment]
Had to rewrite a bit the duplicate picker to fix an issue in some cases when you have multiple duplicated issue.
And because of this the testing scope has to be increased;
- Payouts upload modal (csv), when you upload a file with invalid data, ex: invalid email format or not allowed amount
- Voucher create modal: when you try to create a new voucher with and assign it to a bsn or email which already has a voucher
- Vouchers upload modal: when you try to upload vouchers assigned to a bsn or email which already has a voucher or the amount is less or equal to 5
- Prevalidation upload: when you upload a new prevalidation for a uid which already has a prevalidation, it should update the values of the existing prevalidation and not create a new prevalidation

**Comment by irinaBerendeeva87** [comment]
@aghimpu  Please resolve the conflicts

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
 **Payouts upload modal (CSV)**
✅ CSV file with not allowed amount
❌ error text when the CSV file has an invalid email format 
Screenshot 2024-10-01 at 10 56 14
**I think it could be in this format:
Row number: incorrect value - error message with a hint** 

❌ If the CSV file has incorrect IBAN and correct email then the email is present in the error message 
Screenshot 2024-10-01 at 10 50 36

**Voucher create modal**
✅  create a new voucher with and assign it to a BSN or email that already has a voucher
 
**Vouchers upload modal:**
❌❓ Don't count a case when a requester got a voucher via a fund application by himself. 
✅  when you try to upload vouchers assigned to a BSN or email that  the amount is less or equal to 5

✅Prevalidation upload: when you upload a new prevalidation for a uid that already has a prevalidation, it should update the values of the existing prevalidation and not create a new prevalidation
❌ when I upload the same file with changed values  second time it doesn't update the values of the existing prevalidation 

https://github.com/user-attachments/assets/11b6b40a-4bb8-4264-8ddd-354e041b442b

❌ Translations   
this modal only in english
Screenshot 2024-10-01 at 11 06 12

**Comment by aghimpu** [comment]
>> Don't count a case when a requester got a voucher via a fund application by himself.
>> when I upload the same file with changed values second time it doesn't update the values of the existing prevalidation

I think these should be out of scope for now, we didn't have them in the requirements and I'm not even sure if we really need it. They would increase the initial scope too.

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-backend/pull/2343

**Comment by irinaBerendeeva87** [comment]
> > > Don't count a case when a requester got a voucher via a fund application by himself.
> > > when I upload the same file with changed values second time it doesn't update the values of the existing prevalidation
> 
> I think these should be out of scope for now, we didn't have them in the requirements and I'm not even sure if we really need it. They would increase the initial scope too.
As I understood from Valentins' comment   it's in the scope :
Vouchers upload modal: when you try to upload vouchers assigned to a bsn or email **which already has a voucher** or the amount is less or equal to 5

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
Checked:
❌ text error message  when the CSV file has an amount =5 
Screenshot 2024-10-07 at 14 19 12

**Fixed**
- error text when the CSV file has an invalid email format
- If the CSV file has incorrect IBAN and correct email then the email is present in the error message
-  when I upload the same file with changed values second time it doesn't update the values of the existing prevalidation
✅ no errors in the console
✅ error 422 
✅ checked in different implementations

**Comment by aghimpu** [comment]
@irinaBerendeeva87 did you deploy the back-end branch as well? because the error message was fixed there, as the validation error comes from there. Above I posted a link to the back-end branch

**Comment by irinaBerendeeva87** [comment]
> @irinaBerendeeva87 did you deploy the back-end branch as well? because the error message was fixed there, as the validation error comes from there. Above I posted a link to the back-end branch

Yes I did it)
Screenshot 2024-10-07 at 15 48 19

**Review by irinaBerendeeva87 — DISMISSED** [review]
all comments have been fixed

**Comment by lexlog** [comment]
@aghimpu can you please check merge conflict

**Review by irinaBerendeeva87 — APPROVED** [review]
### Double checked:  
✅ modal has right error messages:
Screenshot 2024-10-25 at 10 45 44

✅ no unexpected errors in the console
✅ error 422

**Pull request merged**
