### PR TITLE
read-speaker integration

### PR DESCRIPTION
**Pull request by dev-rminds**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: read speaker
pages
✅ home
✅ funds
✅ aanbieders(list)
❌ aanbieders(map)
the reader overlapped the text 
Screenshot 2024-11-01 at 13 43 19

❌ Inloggen/Start aanvraag

Screenshot 2024-11-01 at 13 45 10
Screenshot 2024-11-01 at 13 45 21

❌ fund detail page 
❌ element "/" on breadcrumbs 
Screenshot 2024-11-01 at 13 54 20
❌ fund request page 
Screenshot 2024-11-01 at 14 39 13


❌Identity confirmation via digId
Screenshot 2024-11-01 at 13 53 46

❌  Recover account
Screenshot 2024-11-01 at 13 57 41

❌Activation code
Screenshot 2024-11-01 at 14 06 43

✅ uitleg
✅Zoekresultaten
✅ voucher page
✅ Mijn tegoeden
✅ My wishlist
✅ Reservations
✅ declarations
✅ To request
✅ Notifications
✅ Notification preferences
✅ Email settings

❌ about me app
Screenshot 2024-11-01 at 14 19 38
❌ Log in op de app 
can read only highlighted words
Screenshot 2024-11-01 at 14 19 12

❌Register as a provider
Screenshot 2024-11-01 at 14 26 08
❌ provider information page 

Screenshot 2024-11-01 at 14 28 03

❌ Make a reservation
Screenshot 2024-11-01 at 14 46 14

✅ no errors in the console
✅ error 422 and 429
✅ checked in different implementations

--------------------------
 
 **Not related to this PR**
 page sessions while GET request returns 500 Internal Server Error
 
Screenshot 2024-11-01 at 14 13 21

 <details>  <summary>backend laravel log</summary>  [2024-11-01 14:12:20] local.ERROR: Attempt to read property "created_at" on null {"userId":"0x601b798a7ccb0f27bce2c92e520b593aa14e6dcb","exception":"[object] (ErrorException(code: 0): Attempt to read property \"created_at\" on null at /var/www/forus-backend/app/Services/Forus/Session/Resources/SessionResource.php:27)
* [stacktrace]
* #0 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
* #1 /var/www/forus-backend/app/Services/Forus/Session/Resources/SessionResource.php(27): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
* #2 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(65): App\\Services\\Forus\\Session\\Resources\\SessionResource->toArray()
* #3 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
* #4 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map()
* #5 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map()
* #6 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(64): Illuminate\\Support\\Collection->map()
* #7 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(102): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
* #8 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(108): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toArray()
* #9 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(19): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve()
* #10 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(134): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse()
* #11 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(114): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse()
* #12 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(902): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse()
* #13 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(887): Illuminate\\Routing\\Router::toResponse()
* #14 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Routing\\Router->prepareResponse()
* #15 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
* #16 /var/www/forus-backend/app/Services/Forus/Auth2FAService/Middleware/Auth2FAMiddleware.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #17 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Services\\Forus\\Auth2FAService\\Middleware\\Auth2FAMiddleware->handle()
* #18 /var/www/forus-backend/app/Http/Middleware/ApiAuthMiddleware.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #19 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ApiAuthMiddleware->handle()
* #20 /var/www/forus-backend/app/Services/Forus/Session/Middleware/ForusSessionMiddleware.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #21 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Services\\Forus\\Session\\Middleware\\ForusSessionMiddleware->handle()
* #22 /var/www/forus-backend/app/Http/Middleware/ClientVersionMiddleware.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #23 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ClientVersionMiddleware->handle()
* #24 /var/www/forus-backend/app/Http/Middleware/ClientTypeMiddleware.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #25 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ClientTypeMiddleware->handle()
* #26 /var/www/forus-backend/app/Http/Middleware/ImplementationKeyMiddleware.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #27 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ImplementationKeyMiddleware->handle()
* #28 /var/www/forus-backend/app/Http/Middleware/DomainMiddleware.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #29 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\DomainMiddleware->handle()
* #30 /var/www/forus-backend/app/Http/Middleware/LocaleMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #31 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\LocaleMiddleware->handle()
* #32 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #33 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
* #34 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #35 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
* #36 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
* #37 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
* #38 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
* #39 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
* #40 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
* #41 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #42 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
* #43 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #44 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
* #45 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #46 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
* #47 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
* #48 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #49 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
* #50 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #51 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
* #52 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
* #53 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #54 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
* #55 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #56 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
* #57 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #58 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
* #59 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
* #60 /var/www/forus-backend/public/index.php(62): Illuminate\\Foundation\\Http\\Kernel->handle()
* #61 {main} "}
 </details>

**Comment by dev-rminds** [comment]
### Changes
- Pushed fixes based on feedback.
- Added breadcrumbs to all pages on the webshop.
- Refactored layout to reduce differences between almost identical pages (fund, provider, and product pages).
- Fixed indents on the sides of some pages (indent was 2 times larger than necessary).
- Resolved issue with breadcrumbs on mobile where the active page was shown as “…” when the name did not fit in one line.
- Fixed back button functionality on fund, provider, and product pages to save filters when returning from details page.

### Additional test scope
- Advised to check CMS pages to ensure correct functionality (e.g., changing the order of text and CMS blocks).
- Ensure pages work normally when disabling the service in .env (no strange indents).
- Optionally check fund, provider, and product pages on other implementations for consistency.

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked :read speaker
**Fixed:**
 - aanbieders(map) for now it is hidden
 - Inloggen/Start aanvraag
 -  fund detail page
 -  element "/" on breadcrumbs
 - Identity confirmation via digId
 - fund request page
 - activation code
 - register as a provider
 - about me app
 - provider information page
 - button "back" on 
 
✅ no errors in the console
✅ checked in different implementations

**For these  will be created another pr :**
- Log in op de app 
- Make a reservation

**Comment by lexlog** [comment]
@irinaBerendeeva87 @dev-rminds 

> For these will be created another pr :

Log in op de app
Make a reservation

can you share plans about this PR, is it in scope of original issue or it is out?

**Pull request merged**
