### PR TITLE
New website

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by lexlog** [comment]
checked website a bit after deployment

minor feedback bugs for @aghimpu :
- [ ] https://dev.forus.io/website/#/website - text is overlapped with block
Screenshot 2024-08-26 at 22 15 40
- [ ] https://dev.forus.io/website/#/ons-verhaal button "request demo"  on the end of the page is not working
- [ ] https://dev.forus.io/website/#/rollen/deelnemer "read our story" button doesn't work
- [ ] https://dev.forus.io/website/#/rollen/aanbieder  "read our story" button doesn't work
- [ ] https://dev.forus.io/website/#/ "less meer" button doesn't work
- [ ] inloggen button text is not placed correctly
Screenshot 2024-08-26 at 22 28 43


questions for @aghimpu and @MariaForus - here are some basic enhancement proposal from current version, which from my perspective must have, but not urgent before release
- [ ] Contact form - should we make checkmark "agree with forus privacy terms" mandatory on contact form? it is not mandatory now, but usually on websites it is
- [ ] Contact form - set mandatory fields with "*" or show optional fields as "optional" to enhance UX
- [ ] add website tab logo
Screenshot 2024-08-27 at 10 03 40
- [ ] Should we hide inloggen button on pages if you are logged in? Since it's not clickable
Screenshot 2024-08-26 at 22 21 15
- [ ] https://dev.forus.io/website/#/cms - Sholud we not direct to the start of page when choosing new tab, so user stays at the same part of page
Screenshot 2024-08-26 at 22 22 07

**Comment by MariaForus** [comment]
@aghimpu answers to your questions: 

- _Contact form - should we make checkmark "agree with forus privacy terms" mandatory on contact form? it is not mandatory now, but usually on websites it is_ --> It should be mandatory as described in the issue. @aghimpu This should be fixed **before** going live.

- _Contact form - set mandatory fields with "*" or show optional fields as "optional" to enhance UX_ —> Agree, important point, but this can be improved **after** going live

- _Contact form - it is possible to fill in characters in phone number, should we add phone number validation?_ —> Yes, definitely. Can be improved **after** going live.

- _add website tab logo_ - Yes, very good point, favicon should be added **before** going live. @aghimpu Let's use the same one we have on the current website. 

- _Should we hide inloggen button on pages if you are logged in? Since it's not clickable_ - Yes, can be improved **after** going live.

-  _Sholud we not direct to the start of page when choosing new tab, so user stays at the same part of page_ -> Very good idea, let’s do this **after** the website is live.

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-backend/pull/2286
https://github.com/teamforus/forus-backend/pull/2287

**Comment by MariaForus** [comment]
### Website feedback 27.08 @aghimpu 

**Privacyverklaring**

- [ ] There is no CTA at the bottom of the picture

How it is now: 
image

How it should be:
image

- [ ] There are missing spaces between words (via [info@forus.io](mailto:info@forus.io)) 3 times
image

- [ ] There is a missing link (see Figma file)

Missing link: https://autoriteitpersoonsgegevens.nl/nl/contact-met-de-autoriteit-persoonsgegevens/tip-ons
image

**Contact page**

- [ ] Social link don’t work
image

- [ ] In the form, we should add a link to the privacyverklaring (both this form and Book a demo form)

image

- [ ] The field for "telefoon" is too big and different than in the design

How it is now: 
image

How it should be: 
image

- [ ] When you fill in the contact form - the "thank you" text appears a bit pushed (see the design) 

How it is now: 
image

How it should be: 
image

**Nav bar**

- [ ] "Inloggen" is not clickable - it should lead to the log in page

image

**Gratis demo**

- [ ] Form - I tested the form and I don’t receive a message to [info@forus.io](mailto:info@forus.io) when I fill in the form. This is both for the Contact form and Gratis demo form.

**Comment by aghimpu** [comment]
> * Form - I tested the form and I don’t receive a message to [info@forus.io](mailto:info@forus.io) when I fill in the form. This is both for the Contact form and Gratis demo form.

This is pretty weird that you didn't receive an email. The response from the backend seems fine, but I'm not sure if the backend changes were also deployed by @lexlog (there's a branch for the contact form which adds some extra fields and changes the email a bit).

**Comment by aghimpu** [comment]
@lexlog the contact form privacy checkbox was already mandatory, please check the backend branch https://github.com/teamforus/forus-backend/pull/2286

Btw there's also a backend branch for login pages - https://github.com/teamforus/forus-backend/pull/2287.
May be we should combine them into one branch later as well.

**Comment by MariaForus** [comment]
### Website feedback 28.08.2024
@aghimpu 

**Nav bar**

- [ ] "Lees meer" button in “Nog meer vragen” part should lead to the helpcenter, now it's not clickable
image

**Basic features overview**

- [ ] The image in the hero section cuts off in a weird way 
image

**Fondsen**

- [ ] The image in the hero section cuts off weirdly
image

- [ ] The same image (hero section) is missing alt text. The alt text should be: "Regelingen opzetten en beheren via het Forus-platform"

- [ ] This 2nd image is missing icons 

How it is now:
image

How it should be: 
image

- [ ] This image has the wrong alt text it should be: "Opzetten van een fonds in het Forus-platform"
image

- [ ] From what I understood in the design, those options with arrows should be clickable, and the images would change according to what you click. @sashooa do we have those images ready? @aghimpu If not, let’s remove the arrows for the MVP and add them and the images later on. 

image

- [ ] This image has the wrong alt text. It should be: "De beoordelaarsrol in het Forus-systeem stelt medewerkers in staat om aanvragen effectief te evalueren"
image

- [ ] There is a wrong image for this section. Please check the design

How it is now: 
image

How it should be: 
image

**Comment by aghimpu** [comment]
Update:

All the feedback except the one from today is done. Also some suggestions that aren't mandatory yet for going live are omitted. 

The email from contact form not being received needs investigation (could be because the backend wasn't deployed or env configuration issue, perhaps EMAIL_FOR_CONTACT_FORM isn't set as info@forus.io in the env file ?)

**Comment by MariaForus** [comment]
### Website feedback 28.08.2024 
@aghimpu 

**Website** 

- [ ] The text and image in the hero section cut off in a weird way

- [ ] The same image in the hero section is missing alt text
image

- [ ] There are weird signs in the text, they should be removed
image

- [ ] The 3 images that appear when choosing different arrow are missing alt text. Please check Figma file
image

- [ ] This should link to CMS page, also this image has the word alt text. It should be “Organisatiehuisstijl zelf aanpassen met behulp van het Content Management Systeem”
image

- [ ] This image also has the wrong alt text. It should be: "Bewerken van content met behulp van het CMS"
image

**CMS**

- [ ] The image in the hero section is missing alt text. It should be: "Websites in real-time bewerken met Content Management Systeem"

- [ ] The images in this section are missing alt texts, please see Figma file
- [ ] Lees meer button should lead to “website” page
image

- [ ] "Content aanpassen" and text below is differently aligned than in design. It should be aligned to the left

How it is now: 
image

How it should be:
image

- [ ] “webpage’s” has the apostrophe in the wrong direction. It should be “webpagina’s”

image

**Me-app**

- [ ] We need to have a new image in the hero section. @sashooa is making a new version. Please let @aghimpu know when it’s ready
image

- [ ] The image in the hero section is missing alt text. It should be: "Tegoeden zichtbaar in de Me-app"

- [ ] In the “feature overzicht” part there are CTA’s missing 
- [ ] In the same section images are missing alt text, please check Figma file. 
How it is now: 
image

How it should be: 
image

- [ ] Download me-app buttons for Google play and App Store don’t work. 
- [ ] We need a new image for this CTA. @sashooa is making a new version. Please let @aghimpu know when it’s ready
image

**Managementinformatie**

- [ ] The image in the hero section is missing alt text. It should be: "Statistieken pagina's in het Forus-platform"

- [ ] This word should link to the sponsor page
image

- [ ] This image is missing the icons as the design

How it is now:
image

How it should be: 
image

- [ ] This text should be aligned the the left as in design

How it is now: 
image

How it should be:
image

**Homepage**

- [ ] I see weird lines on the homepage. I thought it was my monitor, but I also see it on other people’s laptops. @aghimpu can you please check it out and remove the lines?
image

**Comment by lexlog** [comment]
@aghimpu thanks for fixes
@MariaForus - new version is deployed on https://dev.forus.io/website/#

re-evaluation of my previous feedback, that were not fixed:

- [ ] "https://dev.forus.io/website/#/rollen/deelnemer - aanvragen/delneemer tab title layout is moved to the right" - this point was about missed space on mobile version for icon title
Screenshot 2024-08-28 at 11 46 50
- [ ] "https://dev.forus.io/website/#/managementinformatie mobile version - last tab item name is not visible" now label. is disappeared
Screenshot 2024-08-28 at 11 51 18

- [ ] "Contact form - set mandatory fields with "*" or show optional fields as "optional" to enhance UX" - privacy statement is still not having red "*"
- [ ] "add website tab logo" - not yet there

additional note for @MariaForus - i deployed backend, so contact form email works 
Screenshot 2024-08-28 at 11 50 29

new findings
- [ ] https://dev.forus.io/website/#/ - "Bekijk basisfuncties van ons system" button doesn't work
- [ ] https://dev.forus.io/website/#/website - layout overlay on responsive version
Screenshot 2024-08-28 at 11 39 43

- [ ] one of funds with long name have image layout broken
telegram-cloud-photo-size-2-5366599406750655408-y

- [ ] funds points slider doesn't change when changing tabs
telegram-cloud-photo-size-2-5366599406750655407-y
telegram-cloud-photo-size-2-5366599406750655409-y
telegram-cloud-photo-size-2-5366599406750655410-y

question to @MariaForus and @aghimpu:
- [ ] should blue line slider be positioned differently (moved more right each time as a progress bar) by design on different blocks?
telegram-cloud-photo-size-2-5366599406750655411-y
telegram-cloud-photo-size-2-5366599406750655413-y
telegram-cloud-photo-size-2-5366599406750655412-y

**Comment by MariaForus** [comment]
@lexlog thanks! 

- _should blue line slider be positioned differently (moved more right each time as a progress bar) by design on different blocks?_ --> Yes, I think so but @sashooa could you please let us know what was your vision for this?

- @lexlog @aghimpu about the forms and e-mails, I checked it out again and I still don't receive e-mail to info@forus.io, do you know why that can be?

- [ ] I noticed that "Heeft u specifieke vragen..." field is mandatory and it should be optional. @aghimpu can you please adjust that? The required fields are only Naam and E-mail. If someone doesn't fill in those fields they should see this message: _Deze informatie hebben we nodig om uw aanvraag goed te verwerken._
image

- [ ] The text "accept privacy terms dient te worden geaccepteerd should be changed to _"Om verder te gaan, dient u toestemming geven voor het verwerken en opslaan van uw persoonsgegevens."_

**Comment by MariaForus** [comment]
### Website feedback 28.08.2024
@aghimpu 

**Inloggen**

- [ ] The text should be: "Inloggen als aanbieder"
image


- [ ] The text should be: "Inloggen als beoordelaar"
image

- [ ] Aanmelden page is old and a different from in design - the cta’s are missing, as well as links to other pages

How it is now: 
image

How it should be: 
image

- [ ] An e-mail that I received has a weird image, so I want to double-check if this needs to be fixed
image


**Error page**

- [ ] The font is different on this page

image

**Cookie banner**

- [ ] Let’s set Noodzakelijke cookies and Analytische cookies as standard on
- [ ] 'Noodzakelijke cookies' are necessary and can’t be switched off. We should not give people option to switch them off 
image

- [ ] We should add a link to the privacyverklaring here

**Mobile**

- [ ] Cookies banner and text are not properly adjusted and part of the text is missing
image


- [ ] Inloggen button doesn't work on mobile
image


- [ ] There is a different design (with phone) for the mobile version

How it it now: 
image

How it should be:
image


- [ ] 'Reports' should be changed to 'Managementinformatie' but if it's too long it can be changed to 'Statistieken'

image

- [ ] Pages: basicfuncties overview and roles overview are not clickable and accessible in the navigation bar.

**General note**

- [ ] At first I thought we could do this after but it's better to do this **before** webite is live as it's bad for user experiance. The more I check out the website, the more it's an issue 
_Sholud we not direct to the start of page when choosing new tab, so user stays at the same part of page_

**Comment by lexlog** [comment]
@MariaForus 

> @lexlog @aghimpu about the forms and e-mails, I checked it out again and I still don't receive e-mail to [info@forus.io](mailto:info@forus.io), do you know why that can be?

messages are sent to server@forus.io group email, which you are not added in, I resend you the email you generated to your email box

**Comment by MariaForus** [comment]
@lexlog thanks, I received the e-mail. @aghimpu Is it sent to server now because the website is now live yet? As mentioned in the issue, I would like to automatically receive a message to info@forus.io when we go live.

**Comment by MariaForus** [comment]
@aghimpu here is the 1st feedback from @sashooa about the homepage, nav bar and footer (desktop). It's in a document, please let us know if this is an okay way of working for you and if you have any questions

[The feedback about navigation and the homepage (Desktop).docx](https://github.com/user-attachments/files/16795597/The.feedback.about.navigation.and.the.homepage.Desktop.docx)

**Comment by aghimpu** [comment]
> @lexlog thanks, I received the e-mail. @aghimpu Is it sent to server now because the website is now live yet? As mentioned in the issue, I would like to automatically receive a message to [info@forus.io](mailto:info@forus.io) when we go live.

@MariaForus The contact form email is configured in an certain file (.env file) for the specific environment and I have no idea what's the configuration for the dev environment. Aleksei knows more about it since he's doing the configuration part on the dev environment and the deployment. My job was to ensure that the contact form sends an email to the address that is configured in that env file, whatever address it is.

**Comment by lexlog** [comment]
@MariaForus @aghimpu contact form email for production is info@forus.io and is not planning to change, so it will be info@forus.io after release of new website

**Comment by MariaForus** [comment]
### 29.08.2024

**Home**

- [ ] Laten we kennis maken button should lead to the demo page. Not the button doesn't go anywhere
- [ ] The 3 dots should be removed 
image

**Basic features**

- [ ] This was probably mentioned before, but there is a description missing in one feature - "Managementinformatie"
image

**Mobile**

- [ ]  Homepage-unique aspects part- the texts are wrong, only after clicking on particular feature the text changes to correct one. This is for every step there, but I paste 1 example here. The correct text should be viewed by the visitor from the beginning. 
image
image

- [ ] Privacy-verklaring page - there is a missing CTA in the end

How it is now:
image

How it should be:
image

**Comment by sashooa** [comment]
### **Feedback for **[ABOUT US](https://github.com/teamforus/WEB-2023-website-forus/issues/162)** (Desktop)**


About Us 1

1.	(1) The background with circles is missed, (2) the distance between the main Header and subtitle must be less so that (3) our slogan will be visible in a full screen mode , it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1582-9955&node-type=FRAME&t=JBK1ZdQQZdy6WS0K-11  

About Us 2

 2.	(1) The label should be bigger – make all labels from all pages (inclusive homepage) in the same size – see the design, (2) add more distance between label and header, (3) add more distance the header and description, (4) I propose to improve the design a little, let's move the image a bit to the top to be in line with the title, I think we should discuss the position of this image in a meeting, (5) I found that we have problems with all of the shadows across the website why is this so? (6) the titles from the buttons are written with different typefaces, they should be similar – see the design , it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1582-9955&node-type=FRAME&t=JBK1ZdQQZdy6WS0K-11 


 
About Us 3

3.	(1) This block is completely wrong than then it should be, why it’s so? (2) The label should be bigger – make all labels from all pages (Inclusive homepage) in the same size – see the design, (3) the arrows should be square instead of rounded, (4) instead of the dotted line, there should be a "road" with milestones as numbers, as I said before - the design is wrong and must be changed, (5) there is a place for year, (6) and here is a place for the title, (7) and that blue number becomes blue in the Hover state... In the normal state, the number has a gray stroke outline and a white background, it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1582-9955&node-type=FRAME&t=JBK1ZdQQZdy6WS0K-11 


 
About Us 4

4.	(1) Please make less distance between the title and the description of this block, (2) please change the button because it should be wider, it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1582-9955&node-type=FRAME&t=JBK1ZdQQZdy6WS0K-11 


 
About Us 5

5.	(1) I'm not happy with the quality of this image, could you please change it to an SVG file instead of a PNG?


 
About Us 6

6.	(1) The dashed line should not pass under the button, it should reach the button at a distance of +\- 30-40 pixels and continue with the same distance on the other side of the button, please add a free space between the line and the button , it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1582-9955&node-type=FRAME&t=JBK1ZdQQZdy6WS0K-11 (2) could you please change the image to an SVG file instead of a PNG?

**Comment by sashooa** [comment]
### **Feedback for **[Homepage](https://github.com/teamforus/WEB-2023-website-forus/issues/149)** (Desktop)**

Home 1
1. The circles from the background in the header are missing, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1809-18678&t=unEVICFfihSNmjJZ-11 
Home 2
2. the description is written in regular type but it should be a light one, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-979&t=unEVICFfihSNmjJZ-4 
Home 3
3. the label should be smaller in height, the header title should be written in bold instead of black, and the button is too small, it must be wider, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1357-5711&t=unEVICFfihSNmjJZ-4 
Home 4
4. the label should be smaller in height, with less indentation between the label and the Main header title, and less indentation between the icon and the title (Deelnemer, etc...), the button itself is different than in the design (it should be similar), the hover effect of the button is wrong (the color of the color should be lighter - see the design), the grid with four elements that represent roles in our platform was designed very abstractly, the blocks shouldn't have a fixed size, and on hover the arrow from the "read more" link should move forward (to the right side), which means the hover effect is missed, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1135-7331&t=unEVICFfihSNmjJZ-4 
Home 5
5. gradient overlay behind the text is bigger than it should be, Please make it the same as in the design, the font type is different as in the design it should be lighter, and the hover of the button is wrong, please check the design, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1783-126538&t=unEVICFfihSNmjJZ-4 
Home 6
6. Icons have two instances, normal and active - the normal one for the normal tab and the active one for the active tab (please see the layers in the Figma file), the button is different than in the design, and the description text in the blue square is impossible to read because of the other font, please change the typeface - use regular instead of light one, the images don't have the shadow effect - why its missed? , it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=3436-26482&t=unEVICFfihSNmjJZ-4 
Home 7
7. this block works completely differently than we discussed: the blocks with text should appear - one by one by scrolling down, and the circles with the Forus logo should be much bigger than now. Also, each block with text should have a hover effect, and that blue number becomes blue in the Hover state... In the normal state, the number has a gray stroke outline and a white background, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-2347&t=unEVICFfihSNmjJZ-4 
Home 8
8. The implementation title should be aligned on the left side. We also have to play together with you - with the main header and subtitle of each block on the home page, and not only... , it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-11963&t=unEVICFfihSNmjJZ-4

**Comment by sashooa** [comment]
### **Feedback for [Navigation bar & Footer](https://github.com/teamforus/WEB-2023-website-forus/issues/139) (Desktop)**

Drop-down 1
1. I'm not sure if I like how the drop-down appears... The background that appears by Hover over the menu item should have rounded corners (see the design), by clicking on the free space (on the dark overlay area) the drop-down should disappear exactly as if we clicked on the close icon, on hover the arrow from the "Nog meer vragen?" should move forward (to the right side), which means the hover effect is missed, it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1809-18678&t=unEVICFfihSNmjJZ-11 
Drop-down 3
2. The block with a banner about the help center is broken, please remove the space between the image with the browser and the border of the blue base, add more indentation between the title and description of the navigation item, and add more distance between the links and separator in the footer (where are book a demo and login buttons), it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1809-18678&t=unEVICFfihSNmjJZ-11 
Drop-down 2
3. both buttons are extremely big, please make them smaller, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-930&t=unEVICFfihSNmjJZ-4
Home 9
9. Download from Apple and Google store buttons should have a hover effect, in their case the hover is our main dark color, and the button "read more about our platform" should have white hover instead of current which is wrong, it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-12244&t=unEVICFfihSNmjJZ-4 
Home 10
10. Please add more space between sections of the footer to give them a bit more air , it should be as here - https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-12244&t=unEVICFfihSNmjJZ-4

**Comment by sashooa** [comment]
### **Feedback For Roles [Overview](https://github.com/teamforus/WEB-2023-website-forus/issues/148) Page (Desktop)**


Roles Overview 1

1. The distance between the header and subtitle must be less – please see the design, (2) where are the circles on the background in the header part of the website? (3) Wrong font size - must be 20 instead of 18 , it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-20207&t=vFEs8S1KqdHaxMFJ-4
Roles Overview 2
2. (1) wrong typeface and font size of the title, it must be 26 instead of 20, (2) the wrong color, typeface, and font size - must be 16 instead of 14, (3) a minimum distance between the subtitle and the read more button is 50 pixels, (4) please remove the blobs on the background here, they should be only on the homepage... , it should be as here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=970-20316&t=vFEs8S1KqdHaxMFJ-4

**Comment by sashooa** [comment]
### **Feedback For News – [Article Page](https://github.com/teamforus/WEB-2023-website-forus/issues/162) (Desktop):**

News – Article 1
1. (1) The distance between the header and subtitle must be less – please see the design, (2) Where are the circles on the background in the header part of the website? (3) Wrong font size - must be 56 instead of 48, (4) label is missed, see design here – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1371-6637&t=vFEs8S1KqdHaxMFJ-4 
News – Article 2
2. (1) The distance between block "Vervolg fasen" and the call to action should be increased please see the design; (2) where are the circles behind the block "Vervolg fasen" on the Background??? (3) The distance between the title and button should be less, see the design – https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1371-6503&t=vFEs8S1KqdHaxMFJ-4

**Comment by sashooa** [comment]
### Feedback Updates for [Navigation bar + footer](https://github.com/teamforus/WEB-2023-website-forus/issues/139) (Desktop)

Drop-down 4
1. (1) The color of the text is wrong please change it to this one: #93979C, (2) There should be an arrow to make it clear that there is a link... (3) The borders of the hover effect should be rounded, please see the design, (4) Between text and arrow should be a free space please, check the design file:

**Comment by sashooa** [comment]
### Feedback For [Contact Us](https://github.com/teamforus/WEB-2023-website-forus/issues/158) Page (Desktop):



Contact Us 1
1. (1) The distance between image and the header title should be less, (2) the distance between header title and subtitle also must be less, pleas, (3) the distance between subtitle and separation with dashed line and logo of Forus also must be less, please make it as in the design, (4) where are the circles on the background in the header (top) part of the website? (5) Also the banner-image actually is a slideshow and it must have a pagination, please take a look in the design: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1523-9795&t=facVqOXtgOBQqSVj-4
Contact Us 2
2. (1) Make less distance between the separator and header title, (2) Less distance between the header title and the contact details, (3) contact details (below label) don't have an indentation, they should be in line with the label, please move contact details to the right, - see how it is in the design: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1523-9868&t=facVqOXtgOBQqSVj-4 , (4) the distance between icon and label-text everywhere is different please make it the same, (5) the social media icons have a wrong size they should be 50 px instead of 40, (6) where is the shadow that should be on hover effect on the social media icon? (7) please make sure that the distance between the map and contact details is correct (!) in the design the distance is much bigger, so please increase the distance, 
Contact Us 3
3. (1) make less distance between contact details and head up of the support section, (2) The grey base on the background of icons with the contacts must be wider - see the design, (3) The section with 4 icons should be in line with the main header and description, (4) icons must the bigger please see the design, (5) blue hover appears not only while the cursor is above the icon but the whole "square" area should be "hot area" with the hover effect, (6) please increase the distance between support and the header of the contact form... (7) please make less distance between header and subtitle, (8) Why are the circles on the background missing? I didn't approve this design "improvement", so please add the circles.😉 - see how it is in the design: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1523-9821&t=facVqOXtgOBQqSVj-4
Contact Us 4
4. (1) please, increase the distance between support and the contact form, (2) please, make less distance between the header title and description of the contact form, (3) the text placeholders in the inputs should be in the same size on each stage (normal, active, error), (4) the button has a wrong size it should be wider, (5) distance between words should be fixed, please make it smaller, (6) Why are the circles on the background missing?😉
Contact Us 5
5. (1) Button must be smaller, please take a look in the design file: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1557-10377&t=facVqOXtgOBQqSVj-4 , (2) Why are the circles on the background missing?😉

**Comment by MariaForus** [comment]
### 30.08.2024

Talked to @sashooa about the Fonds page the "aanvraagmethode part" with the arrows that for now weren't working. We have a solution and a bit different desgin for this:

How it is now:
image


How it should be: 
image

@aghimpu Sorry for such a late change, we missed it before. Can you please make sure this is adjusted? You can find the new version in Figma.

**Comment by sashooa** [comment]
### Feedback For [Login / Sign-up](https://github.com/teamforus/WEB-2023-website-forus/issues/164) Page (Desktop):


Login 1
1. (1) please, make less space between breadcrumbs and the header title, (2) on the hover effect icons become smaller which is the wrong effect, please keep the same size of the icon always, (3) please, make less space between the description and the title, (4) the button is smaller than it should be - please see the design file, (5) where are the circles on the background in the header (top) part of the website?
Login 2
2. (1) please, make less space between breadcrumbs and the header title, (2) please, make less space between the header title and login form, (3) The button is smaller than it should be - please see the design file, (4) the button is smaller than it should be - please see the design file, (5) where are the circles on the background? 🥲
Login 3
3. Add the white square base behind the QR code, see the design file: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1597-31061&t=LDdXALcIrXrC61iN-4

**Comment by sashooa** [comment]
Feedback For **Privacy Statement** Page (Desktop):


Privacy statement 1
1. (1) please, make less space between the header title and separator, (2) make less space between the separator and banner (3) where are the circles on the background in the header part of the website? Also on this page, the background behind the "circles" has a light gray gradient: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1449-17367&t=LDdXALcIrXrC61iN-4 
Privacy statement 2
2. (1) Where is the hover effect? Please see the design file and make it the same: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=3559-25552&t=yAToLufcpJEr6F0f-4

**Comment by sashooa** [comment]
### Feedback For [404](https://github.com/teamforus/WEB-2023-website-forus/issues/165) Page (Desktop)



1. (1) where are the circles on the background in the header (top) part of the website? (2) wrong typeface and font size of the title, it must be 20 instead of 16, (3) please, make less space between image with owl and the separator.

2. (1) The shadow on the hover effect is missing, (2) on the hover the arrow should move to the right side (to the front), please see the design file: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1379-6908&t=meXOMfjXXGSUsyGt-4 , (3) please make less space between the title and description.

**Comment by sashooa** [comment]
### Feedback For [Book a Demo](https://github.com/teamforus/WEB-2023-website-forus/issues/163) Page (Desktop):


Book a demo 1
1. (1) where are the circles on the background in the header (top) of the website? (2) the distance between the header title and subtitle must be less, (3) the placeholder text in the field must have the same size on each stage - normal, active, or error, (4) The distance between top navigation and header title should be less, (5) The shadow effect of the contact form is wrong, please see the design: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1541-52213&t=mlb9USvhcDB3N5ME-4
Book a demo 2
2. (1) the button has the wrong size it should be wider, (2) The design of the inactive state of the button is different than it should be, please make it as in the design: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1541-52249&t=mlb9USvhcDB3N5ME-4
Book a demo 3
3. (1) The width of the success message block is bigger than the contact form itself please make the width the same as the contact form, (2) The Button must be smaller, please take a look at the design file: https://www.figma.com/design/oDL2mEs3bNBNsXJqJAKBJT/Forus.io-v2.0?node-id=1541-53572&t=mlb9USvhcDB3N5ME-4

**Comment by lexlog** [comment]
@MariaForus hi, we started to prepare new repo for the website 
there is also one change for you to know - we will create new feedback in separate issues in that repo to make it more manageable
@sashooa already moved his feedback there

if you will have a NEW feedback ( after comments above are fixed ), please, take this change in consideration and create an issue there https://github.com/teamforus/forus-website/issues

p.s. @sashooa could you please delete the comments that you already transferred?

**Comment by lexlog** [comment]
comment about one point of @MariaForus 

> An e-mail that I received has a weird image, so I want to double-check if this needs to be fixed

this is a logo of organisation, which you are logging into, it differs accordingnly to organisation logo
so I checkmarked this point as fixed, since no fix needed

**Pull request closed without merging**
