### PR TITLE
add tooltips to the transaction details page

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
**States**
❌ Tooltip looks always in an active state(even if it's not open)
Screenshot 2024-08-28 at 11 25 49

**Size**
❌Tooltip size less than 389px
  Now: width: 300px;
❌ Info icon have  bigger size than checkbox
Screenshot 2024-08-28 at 14 51 59

❌ Info icon is superimposed on text when screen size changes
Screenshot 2024-08-28 at 11 36 35
❌ Large space between icon and title
Screenshot 2024-08-28 at 11 39 18
✅  Texts

**Comment by aghimpu** [comment]
@irinaBerendeeva87 Please ignore those styles in Figma for now. Initially I tried a bit to make it look exactly like in Figma, but it's just not possible at the moment using the default component we have for tooltips. Making those changes would require at least a few more hours on top of the initial estimation and the issue was supposed to be small. I also discussed the issue with @dev-rminds and we agreed on this.

So for now the scope should be just the texts inside the tooltips.

**Comment by irinaBerendeeva87** [comment]
After a discussion with @dev-rminds  possibility of fixing "Info icon is superimposed on text when screen size changes", @dev-rminds  made a commit and fixed this. To fix other items decided to create a separate task for global changes tooltips on dashboard.

**Review by irinaBerendeeva87 — APPROVED** [review]
Approve after fixing: Info icon is superimposed on text when screen size changes

**Pull request merged**
