### PR TITLE
add feature for excluding funds from pre-check results

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [x] *Check that dusk tests are working locally on compatible branch*
- [x] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
**Table on pre-check page**
✅ Fields
✅ infoboxes

**Action menu:**
- delete
❌Confirmation Modal in Dutch end English 

Screenshot 2024-11-28 at 11 22 27

❌ edit
if sponsor while editing change from "No" to "Yes"  the  Explanationfild disappeared in the modal and after click Save, the Explanation text keeps in the Table , fund criteries disappeared and as a result  fund  appeared in precheck result

https://github.com/user-attachments/assets/96458cac-1777-41e6-802e-56b4417fec58

https://github.com/user-attachments/assets/e59ddb31-4e51-47ec-8793-03fcbd7560ee

✅ button "Fonds toevoegen" blocked when possible fund added

**Modal "Fonds toevoegen"**
Dropdown Funds :
✅ sponsor can choose and add internal fund
❌ sponsor can choose and add external fund 
there are no external funds on dropdown 
Screenshot 2024-11-28 at 13 10 36

**Ruled out**
✅ dropdown "Ruled out" have Yes and No
✅ if sponsor choose "Yes"   there is no Explanation and after saving fund   don't appear in the  pre-check  results 
✅ if a sponsor choose "Yes"  the criteria disappear  
✅ if s sponsor choose "No"   appears  Explanation input field  and after saving fund   displayed in the  "pre-check"  results  with fixed outcome (text) from explanation
❌ button "Bevestigen"  don't save changes if a sponsor choose "No" and don't add Explanation

https://github.com/user-attachments/assets/c9d45d21-bd9f-426d-a36f-8bcc7fb061e7

❌ validation for the input field if it's mandatory.
the input field can fit Total characters:1533/No spaces:1230

Screenshot 2024-11-28 at 14 52 52

**Fixed outcome in pre-check result and pdf:**
❌ if "not excluded" + Explanation text in pdf results
Screenshot 2024-11-28 at 16 32 17

✅ when fund not excluded and  have a fixed outcome   in the precheck results page
Screenshot 2024-11-28 at 16 25 39

✅ fixed outcome in the precheck results page 
✅ no errors in the console
✅ error 422

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 fixed all points besides "sponsor can choose and add external fund" could not reproduce, I can see external funds on my local, could you please check if external funds used for testing are configured through fund_config and have implementation?.

@LindaForus could you please provide the translations for the exclusion removal modal?
PS: English texts are incorrect, this modal is displayed when you are removing a fund from exceptions:
image
image

Also could you please check if the pdf for a fund with custom "Explanation" is fine?
I am not sure what text should be shown for "Kans" column when custom "Explanation" is used.
image

**Comment by LindaForus** [comment]
@dev-rminds 

1. Translations for the exclusion removal modal
Title: Fonds verwijderen uit afwijkingen en uitsluitingen
Text: Door het fonds te verwijderen uit de afwijkingen wordt het weer meegenomen in de resultaten van de regelcheck. Op de website wordt het advies voor het fonds aan de gebruiker getoond, gebaseerd op de ingevulde antwoorden.

2. PDF check
3. Text for 'Kans': "Geen advies beschikbaar"

**Comment by dev-rminds** [comment]
@LindaForus @irinaBerendeeva87 Translations updated

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
❌ The picture flashes

https://github.com/user-attachments/assets/6c43a3fe-340a-40da-aed5-7a5db0e02666

**Fixed:**
- translations in Confirmation Moda
- edit(explanation)
- button "Bevestigen" don't save changes if a sponsor choose "No" and don't add Explanation

**Not fixed:**
❌ sponsor can choose and add external fund 
✅
✅ no errors in the console
✅ error 422 and 429
✅ checked in different implementations

@dev-rminds  external funds are configured through fund_config and have implementation.

**Review by irinaBerendeeva87 — DISMISSED** [review]
Checked:
everything was fixed

**Comment by lexlog** [comment]
@dev-rminds could you please check merge conflicts?

**Comment by dev-rminds** [comment]
@lexlog fixed the conflicts but also had to rewrite some code because of the differences between exclude funds from pre-check and show formula products. 

Ideally it would be nice if @irinaBerendeeva87 could check again this pr for both features (only the webshop pre-check page part).

**Comment by dev-rminds** [comment]
Local result page:
image

**Comment by irinaBerendeeva87** [comment]
@dev-rminds @lexlog  I checked) and everything works well)

**Review by lexlog — APPROVED** [review]

**Pull request merged**
