### PR TITLE
Epic SPO

### PR DESCRIPTION
**Pull request by dev-rminds**
## Developers checklist
- [x] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: Tomorrow  continue
✅ Payouts in the **side menu**

**Fund details**
✅ Payment settings 
**Fixed amounts:**
✅ checkboxes
✅ translations
✅  at least one checkbox must be checked for the button "Add a category " to appear
✅ CRUD
**Free amounts**
✅ translations
✅ CRUD
✅ checkboxes
✅ At least one checkbox must be checked for the Min and Max amount fields to appear.
 **errors**
✅ less than min value
✅ more  than max value in min field

**Uitbetalingen page**
✅ hover
✅ sorting
✅ changing counter
✅ column Bulk status should have a status instead of number (column removed)

✅ change of Bulk status from "In de wachtrij (1 dagen) " to "In de wachtrij " and add a payout to the queue after 24 hours

❌ The action menu doesn't have  'Directly proceed to payment' if the payout was canceled. 
Screenshot 2024-09-05 at 14 41 48

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:

**Sponsor**
✅ uploading bulk
Change some data in the already uploaded file

✅ text when the fund does not have any payouts. 
❌ column Description
❌ saving changed data after uploading
When sponsor has uploaded file without a note and then changes the note and  after click "save"  and as a result the new note wasn't save. 

https://github.com/user-attachments/assets/cbc56b46-5fb9-4a99-acc3-588c1b219c70

❌ Sorting fields 
while sorting  "Datum uitbetaald" , " Methode " and "Naar IBAN" I got 422 errors  in a console 
Screenshot 2024-09-06 at 13 24 38
after getting the 422error  other actions lead to 422 errors like  searching 
Screenshot 2024-09-06 at 13 26 32


https://github.com/user-attachments/assets/015aa060-b5f1-46a8-b279-abc1d676e5ea

✅ all filters are work and export also works
✅ statuses

**Comment by dev-rminds** [comment]
####  Changelog: 
- Added the option to append BSN or email relation when creating a payout (both single and CSV upload), and these relations cannot be edited.
- Included payout relation fields in the example CSV.
- Added the payout description to the table and fixed editing.
- Updated the design of the payout details page to match Figma, separating it from the transaction details page to ensure the correct aside menu item is active and the breadcrumb is accurate.
- Renamed the "Betaalopdrachten" page in the providers panel back to "Transacties," including the transaction details page.
- Renamed the "method" column from "Methode" to "Toewijzingsmethode" in the payouts table and added a "relations" column named "Methode" with an info/tooltip.
- Fixed sorting by ex "method" column and added sorting by "relation" column.
- Added a new role, "Payout Manager," with the "manage_payouts" permission, ensuring that the login redirect sends to the correct page and only relevant pages are shown.
- Separated the payouts endpoints, controller, and model in the backend while still using the transactions table.

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked :
**Sponsor dashboard**
 ✅ Creating  fund
✅  adding presets for a new fund

 **Validator  dashboard**

✅ email to the requester with changed amount in it application. 
❌ 403 error. a Validator gets an error when tries to approve the request with missing data but after reloading the page the request accepted. 

https://github.com/user-attachments/assets/3875558e-a4f4-44d9-96bf-f5be855af599

 A requester gets a voucher with changed amount after  getting partly approved request and resending request with missing data 
❌ requester gets full amount . 
Screenshot 2024-09-09 at 16 36 09
Screenshot 2024-09-09 at 16 37 32

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: 
**Double checked:**
**fixed** column Description
**fixed**  saving changed data after uploading
**fixed**  403 error
**fixed** requester gets full amount .
New :
Sponsor:
❌ Pagination

https://github.com/user-attachments/assets/60fcecba-9003-44c2-8207-00a15d6fc559

**New Columns at the table** 
✅Toewijzingsmethode
✅Methode
✅Omschrijving
❌Sorting: 422 error for the column: Datum uitbetaald, Naar IBAN, Omschrijving
❌ error in a console while sorting Methode column and Status ( /organizations/6/payouts)
Screenshot 2024-09-10 at 15 52 06

**Filter**
✅Zoeken
✅Bedrag
✅Status
✅Fonds
✅Vanaf
✅Tot en met
✅Vanaf uitbetaald datum
✅Tot en met uitbetaald datum

**Create Payout**
✅ Payout+ BSN+ Description
✅ Payout+ Email + Description
✅ Payout+ Geen  + Description
✅ Free amount+ BSN+ Description
✅ Free amount+ Email + Description
✅ Free amount+ Geen  + Description
❌ Amount field has multiple error messages with a different  max value  when  fund has a max of 1000:
"Hoeveelheid mag niet groter zijn dan 1000.00." and 
Screenshot 2024-09-10 at 11 39 38

 **Updating Payout**
✅ new  description  added
❌ error message when not to chosen value in Amount field. 
when change Toewijzingsmethode from Free amount to Preset but not to choose one of the presets click Save button there is no error message and old value is not changed

https://github.com/user-attachments/assets/0b41fd08-bf3d-4c73-a11d-e03c9bb1e008 

**Payout details page** 
Translations 
❌ field Overgemaakt naar has "transaction.payment_type..title"

**Payout manager**
✅ has access  to see only Uitbetalingen and Activiteitenlogboek pages
✅ can create,update , cancel, direct proceed to payment
✅ can upload csv file

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 resolved the conflicts from front and back

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked:
**Payout details page**
Translations
✅ field Overgemaakt 
✅ Updating Payout
✅ Create Payout
New Columns at the table
✅ Sorting
✅ Pagination

**Pull request merged**
