### PR TITLE
WCAG improvements for elements like checkboxes, toggles

### PR DESCRIPTION
**Pull request by ateamcms**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
**Logged out state**
✅ dropdowns
✅ search button (Nijmegen) accessible by keyboard 
❌ search field doesn't have a  focus

https://github.com/user-attachments/assets/ad4a1f67-367c-4f5b-9b3c-2f7077e0284f

**Logged in state**
✅ My vouchers page (button)
❌ search button (Nijmegen) is not accessible by the keyboard
✅ dropdowns
❌ Submit a declaration modal - not focusable buttons Cancel and To confirm 
✅ Notifications preferences (toggles for notifications)
✅ Search results page (checkboxes)
✅ Declarations
✅new declarations - upload file:
✅arrow left
✅arrow right
✅"." button between arrows
✅turn image left
✅turn image right
✅add more images

 **Not related to this PR**
❌ "Terminate session" on page Sessions not accessible by keyboard
❌ the button "Add Email" has no focus at /identity-emails page 
❌ the button "Enable" has no focus on/2fa page 
❌ the field choose country code and enter phone number fields don't have a separate focus

**Comment by lexlog** [comment]
based on comment of Irina let's increase scope a bit by including non related to issue elements to fix as well (because list is relatively small, but will increase wcag )

**Comment by lexlog** [comment]
note for @irinaBerendeeva87 - latest changes of @ateamcms require test on different implementations, because there was changed order of elements in HTML

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked:
**Logged in state**
✅ search button (Nijmegen) is accessible by the keyboard
✅  Submit a declaration modal -  buttons "Cancel" and "To confirm" are focusable
✅ "Terminate session" on page Sessions accessible by keyboard
✅ the button "Add Email" has focus at /identity-emails page
✅ the button "Enable" has focus on/2fa page
✅  the field choose country code and enter phone number fields don't have a separate focus (fixed if on the opened modal go back)

**Logged out state**
❌ search field doesn't have a focus 
Search field in Nijmegen will not be changed now and we will leave as it works now  due to the limitations of the current solution,  so when clicking on the search icon will not read by TAB and will start reading when all elements under search field pass


 
 **Not related to this PR**

**Pull request merged**
