### PR TITLE
combine voucher pages

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by dev-rminds** [comment]
@aghimpu could you please update dusk tests?

**Comment by aghimpu** [comment]
> @aghimpu could you please update dusk tests?

https://github.com/teamforus/forus-backend/pull/2271

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
**Header and table*:
✅  Sidebar  has only "Tegoeden"
**Aanmaken**
❌ Translations for info boxes
Screenshot 2024-08-08 at 11 22 11



 **fields**
✅  mandatory fields


**Upload bulkbestand**
❌ Translations for info boxes
sometimes errors in the console when trying to download example

https://github.com/user-attachments/assets/7200e4b9-72e4-468b-88ee-1c312a557c71
✅ positive cases
 
 Unclear should we save the state in a previous step

https://github.com/user-attachments/assets/3dae9cf5-68d2-405b-8c32-105ca42e2eca
 
 From @lexlog 
❌  vertical lines 
 
image



Out of scope to fix:
❌  500 error (needs investigation) 


❌ 0 on creating a voucher and writing that is not reproducible already
image

❌  Dropdowns(known issue)
Screenshot 2024-08-08 at 13 36 19

❌ translation for error
Screenshot 2024-08-08 at 13 34 05

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 
> ❌ vertical lines
> 
> image

Top scrollbars are not part of the current feature and they are also out of line in design (guess because the scrollbar and headers are different heights and the buttons should be square)
image

**Comment by lexlog** [comment]
@aghimpu please add translations from figma ( I tried but not succeed due to some styles needed in texts )

**Comment by lexlog** [comment]
tested:
- [x] create one budget voucher ( email, activation code, bsn )
- [x] create one product voucher ( email, activation code, bsn )
- [x] open budget/product voucher details
- [x] create and open subsidy voucher details
- [x] upload csv with budget vouchers
- [x] upload csv with product vouchers
- [x] upload for all funds
- [x] upload for specific fund
- [x] activate
- [x] deactivate
- [x] filters
- [x] tooltpis

**Review by lexlog — APPROVED** [review]

**Review by lexlog — APPROVED** [review]

**Pull request merged**
