### PR TITLE
Add provider products required for funds and notification modal for provider

### PR DESCRIPTION
**Pull request by ateamcms**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by irinaBerendeeva87** [comment]
@ateamcms, please resolve the conflicts.

**Comment by ateamcms** [comment]
@irinaBerendeeva87 done

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: 
**Sponsor dashboard:**
✅ checkbox
✅ tooltip 
✅ text

**Provider dashboard**
✅ pop-up appears if a provider has applied for a fund that has this new requirement.
✅ The pop-up stays till they have created an offer, even if they have been accepted.
✅ Provider can not remove the pop-up till they created an offer.
❌ The pop-up does not vanish after creating  an offer 
Screenshot 2024-09-03 at 16 07 54
✅  The pop-up disappears when a sponsor is unchecked for this requirement. 

✅ The number of organizations increase in dropdown
Screenshot 2024-09-03 at 16 31 13

**Comment by ateamcms** [comment]
@irinaBerendeeva87 fixed  "The pop-up does not vanish after creating an offer" (on backend)

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked:
✅ the modal provider-products-required appeared
✅ the modal provider-products-required appears next day when 
 click Show again tomorrow 
✅ Modal cannot be closed by the provider at all
✅ The pop-up vanished after creating  an offer
✅ After deleting the only one offer the pop-up and modal appeared again

**Pull request merged**
